### PR TITLE
Contrained random assembly program generation

### PR DESCRIPTION
**Pull request by tjarker**
This is the first rough version of a constrained random assembly program generation library. 

It can generate assembly sequences for the complete Leros ISA. The instruction stream is constrained by defining a distribution of instruction categories. Memory access can be constrained to different memory regions and IO interactions to port number ranges.

One feature which is wip for now, is a working branching system which generates branch targets inside of program bounds.

Two examples are given in [`LerosExample.scala`](https://github.com/chiselverify/chiselverify/blob/cr_assembly_gen/src/main/scala/chiselverify/assembly/examples/LerosExample.scala).

### CODE REVIEW

**Comment by Dobios** [comment]
Looks cool, however you need to document your code and please add tests to prove the correctness of you work.
Otherwise everything looks good, but again it would be nice to have tests to see your work in action.

**Review by Dobios — CHANGES_REQUESTED** [review]
Comments would be nice and so would tests.

**Comment by tjarker** [comment]
I added documentation and tests. I also wrapped up the work on the last missing feature concerning the control of the jumping behavior of the generated programs.

**Comment by Dobios** [comment]
Thanks, for adding the comments and tests, it makes it much easier to understand what's going on in your code and how to actually use everything. 
On that end it all looks good to me! I will approve it for a merge, and you can merge whenever you're ready. 

I will just request that, once it has been merged, you [add a page in the wiki](https://github.com/chiselverify/chiselverify/wiki) detailing how to use your program generator and show a couple of examples. It would also be much appreciated if you can also add some details on how you went about implementing it, but please clearly separate the two to avoid confusion.

**Review by Dobios — APPROVED** [review]

**Pull request merged**
